WIN_DIMS = (1280-320,720)
MENU_SIZE = 50
BARS_SIZE = 70
STATS_SIZE = 300
CELL_SIZE = 10
HEALTH_BAR_WIDTH = 500
HEALTH_BAR_HEIGHT = 30

TEAM_A = 'Poland'
TEAM_B = 'Germany'

WARRIOR = 'Warrior'
HUSSAR = 'Hussar'
SFMAX = 1280

### AGENTS ###

# warrior
WARRIOR_HEALTH = 10
MAX_DAMAGE_WARRIOR = 6

#archer
ARCHER_HEALTH = 7
ARCHER_RANGE = 10
MAX_ARCHER_SHOT_DAMAGE = 4
MAX_ARCHER_DAMAGE = 5

# artillery
ARTILLERY_HEALTH = 20
MAX_ARTILLERY_DAMAGE = 16
ARTILLERY_RANGE = 40

# hussar
HUSSAR_HEALTH = 17
HUSSAR_SPEED = 3
HUSSAR_MIN_DAMAGE = 3
HUSSAR_MAX_DAMAGE = 9
HUSSAR_N_TARG_MULTIP = 4
HUSSAR_MAX_LOOP_COUNTER = 2 * HUSSAR_SPEED
HUSSAR_SLOW_DOWN_CHANCE = 10 # xx%
HUSSAR_COLOR_A = (255, 0, 255)
HUSSAR_COLOR_B = (184, 20, 184)

#fog
SHOOT_RANGE = 2
